# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPRUEBAELMERCURI():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pRUEBAELMERCURI(self):
    self.driver.get("https://digital.elmercurio.com/2021/05/19/A")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "#openPram > .sec_txt_header").click()
    self.driver.find_element(By.ID, "txtUsername").click()
    self.driver.find_element(By.ID, "txtUsername").send_keys("rmatiasgomezc@gmail.com")
    self.driver.find_element(By.ID, "txtPassword").send_keys("fondecyt")
    self.driver.find_element(By.ID, "gopram").click()
  
